import { useEffect } from 'react';
import { Link, Navigate, useParams } from 'react-router';
import {
  ArrowLeft,
  Building2,
  Cookie,
  ExternalLink,
  FileCheck2,
  Info,
  LockKeyhole,
  Mail,
  Scale,
  ShieldCheck,
  UserRoundCheck,
} from 'lucide-react';
import logoFullColor from '@/assets/brand/logo/logo-full-color-transparent.png';
import { cn } from '@/shared/ui/cn';
import {
  isLegalDocumentSlug,
  LEGAL_NOTICE_STATUS,
  LEGAL_NOTICE_VERSION,
  LEGAL_ROUTES,
  type LegalDocumentSlug,
} from './legal';

type Section = {
  heading: string;
  body: React.ReactNode;
};

type LegalDocument = {
  title: string;
  summary: string;
  icon: typeof ShieldCheck;
  sections: Section[];
};

const privacySections: Section[] = [
  {
    heading: 'Who is responsible for your information',
    body: (
      <>
        <p>
          The responsible party is the Phatsema legal entity that determines why and how this
          portal processes personal information. The relationship between Phatsema Projects &amp;
          Supplies and Phatsema Mining, the responsible legal entity, its registered address, and
          its Information Officer details must be confirmed before this notice is approved for
          production.
        </p>
        <p>
          Valo Systems may act as a technology service provider and operator where appointed under
          a written agreement. Phatsema remains responsible for its processing purposes and user
          access decisions.
        </p>
      </>
    ),
  },
  {
    heading: 'Information the portal processes',
    body: (
      <ul>
        <li>Identity and work-profile details, including names, email address, phone, job title, department, and biography.</li>
        <li>Employment access details, including role, account status, assigned sites, and effective permissions.</li>
        <li>Authentication and account activity, including successful sign-in time and essential session data.</li>
        <li>Inventory, asset, transfer, stock-count, approval, and administration actions linked to the user who performed them.</li>
        <li>Audit records needed to show what changed, when it changed, and who performed the action.</li>
        <li>Technical security data, such as IP address and browser information, where server security logging is enabled.</li>
      </ul>
    ),
  },
  {
    heading: 'Where the information comes from',
    body: (
      <p>
        Information may be supplied by you, an authorised Phatsema administrator, or generated by
        your use of the portal. If an approved workforce or identity system is connected later,
        this notice must be updated before that integration is enabled.
      </p>
    ),
  },
  {
    heading: 'Why the information is used',
    body: (
      <ul>
        <li>To authenticate users and enforce role and site access.</li>
        <li>To operate multi-site inventory, transfer, count, asset, and approval workflows.</li>
        <li>To maintain accurate records and operational accountability.</li>
        <li>To investigate incidents, prevent misuse, secure the portal, and support external audits.</li>
        <li>To meet contractual, employment, regulatory, and legal obligations.</li>
      </ul>
    ),
  },
  {
    heading: 'Required and optional information',
    body: (
      <p>
        A full name, login email, role, account status, and applicable site access are required to
        provide portal access. Preferred name, work phone, and biography are optional in the
        current portal. If required account information is not provided, Phatsema may be unable to
        create or maintain access.
      </p>
    ),
  },
  {
    heading: 'Who may receive the information',
    body: (
      <p>
        Access is limited according to job responsibilities and may include authorised Phatsema
        managers, administrators, audit personnel, and approved service providers. Information may
        also be disclosed to regulators, law-enforcement bodies, or other recipients where
        authorised or required by law. The final operator and sub-operator register must be
        confirmed before production approval.
      </p>
    ),
  },
  {
    heading: 'Retention and cross-border processing',
    body: (
      <p>
        Personal information must be kept only for as long as needed for the stated purposes,
        legal obligations, dispute handling, and approved record-retention rules. Phatsema must
        approve the detailed retention schedule and confirm hosting locations and any cross-border
        processing before the production notice is finalised.
      </p>
    ),
  },
  {
    heading: 'Security and audit records',
    body: (
      <p>
        The portal uses authenticated sessions, role-based permissions, site scoping, CSRF
        protection, HTTPS in production, and audit records. No system can guarantee absolute
        security. Suspected loss, unauthorised access, or misuse must be reported immediately using
        the approved privacy or security contact.
      </p>
    ),
  },
  {
    heading: 'Your rights',
    body: (
      <p>
        Subject to POPIA and other applicable law, you may ask whether Phatsema holds your personal
        information, request access or correction, object to certain processing, or request
        deletion where the information is no longer lawfully required. You may also complain to
        Phatsema&apos;s Information Officer or the Information Regulator. Some records cannot be
        changed or deleted where they must be retained for audit, security, contractual, or legal
        reasons.
      </p>
    ),
  },
  {
    heading: 'Cookies and automated decisions',
    body: (
      <p>
        The current portal uses essential session and CSRF cookies needed for sign-in and security.
        It does not use advertising cookies or make decisions that have legal or similarly
        significant effects solely by automated means. This notice must be reviewed if analytics,
        optional cookies, or automated decision-making are introduced.
      </p>
    ),
  },
];

const acceptableUseSections: Section[] = [
  {
    heading: 'Authorised access',
    body: (
      <p>
        Access is limited to authorised Phatsema personnel, approved service providers, auditors,
        and explicitly approved demonstration participants. Use only your own account and the
        access assigned to you. Never share credentials or allow another person to work under your
        identity.
      </p>
    ),
  },
  {
    heading: 'Responsible use',
    body: (
      <ul>
        <li>Enter accurate, complete, and timely operational information.</li>
        <li>Use personal and confidential information only for an authorised business purpose.</li>
        <li>Follow approval, segregation-of-duties, stock-control, safety, and site procedures.</li>
        <li>Protect downloaded or exported information and share it only with authorised recipients.</li>
        <li>Report suspected errors, credential exposure, security incidents, or unauthorised access immediately.</li>
      </ul>
    ),
  },
  {
    heading: 'Prohibited use',
    body: (
      <ul>
        <li>Do not attempt to bypass permissions, inspect another user&apos;s restricted data, or probe the service.</li>
        <li>Do not upload malicious content, disrupt availability, or use the portal for unlawful activity.</li>
        <li>Do not manipulate stock, approval, audit, or user records to conceal an action or mislead another person.</li>
        <li>Do not copy, export, or disclose information beyond your approved business need.</li>
      </ul>
    ),
  },
  {
    heading: 'Monitoring and accountability',
    body: (
      <p>
        Portal activity may be recorded and reviewed for operational control, security, support,
        investigations, compliance, and audit. Monitoring must remain proportionate, lawful, and
        consistent with approved Phatsema policies. Actions performed through your account may be
        attributed to you.
      </p>
    ),
  },
  {
    heading: 'Portal disclaimer',
    body: (
      <p>
        This portal supports operational record-keeping and does not replace approved safety,
        financial, procurement, employment, or emergency procedures. Users remain responsible for
        checking safety-critical and financially material decisions against authorised source
        documents and procedures. Demonstration data is fictional and must never be used for live
        operations. Nothing in this disclaimer limits rights or duties that cannot lawfully be
        limited.
      </p>
    ),
  },
  {
    heading: 'Availability and enforcement',
    body: (
      <p>
        Access may be suspended for maintenance, security, investigation, employment changes, or
        suspected misuse. Breaches may lead to access restriction, investigation, disciplinary
        action, contractual remedies, or legal action as applicable.
      </p>
    ),
  },
];

const paiaSections: Section[] = [
  {
    heading: 'Access to records',
    body: (
      <p>
        The Promotion of Access to Information Act, 2000 provides a process for requesting access
        to records held by a private body where the legal requirements are met. A request for
        records is different from a routine request to view or correct your own profile in the
        portal.
      </p>
    ),
  },
  {
    heading: 'Phatsema PAIA Manual',
    body: (
      <p>
        The applicable Phatsema legal entity, its PAIA Manual, request address, Information
        Officer, fees, and available categories of records are still to be confirmed. The approved
        manual should be published here and made available at the required business address before
        this portal is treated as production-ready.
      </p>
    ),
  },
  {
    heading: 'How to submit a request',
    body: (
      <ol>
        <li>Identify the correct Phatsema legal entity that holds the requested record.</li>
        <li>Use the prescribed request form and provide enough detail to identify the record.</li>
        <li>Explain the right you seek to exercise and why the record is required to exercise or protect it.</li>
        <li>Submit the request to the approved Information Officer contact and pay any lawful fee when requested.</li>
      </ol>
    ),
  },
  {
    heading: 'Official guidance',
    body: (
      <p>
        The Information Regulator publishes guidance, prescribed forms, and registered PAIA
        manuals. Requests may be granted, partly granted, or refused in accordance with PAIA.
      </p>
    ),
  },
];

const contactSections: Section[] = [
  {
    heading: 'Phatsema privacy contact',
    body: (
      <div className="rounded-lg border border-warning/30 bg-warning-soft p-4">
        <p className="font-semibold text-warning">Confirmation required before production</p>
        <p className="mt-1">
          The responsible legal entity, Information Officer and Deputy Information Officer names,
          physical address, privacy email address, and telephone number have not yet been confirmed.
          Until approved particulars are published, users should raise privacy and access requests
          through their authorised Phatsema administrator.
        </p>
      </div>
    ),
  },
  {
    heading: 'Information Regulator',
    body: (
      <>
        <p>
          If a concern is not resolved, a data subject may submit a complaint to South
          Africa&apos;s Information Regulator using its published complaint process.
        </p>
        <a
          className="mt-3 inline-flex items-center gap-2 font-medium text-primary hover:underline"
          href="https://inforegulator.org.za/complaints/"
          target="_blank"
          rel="noreferrer"
        >
          Information Regulator complaints
          <ExternalLink aria-hidden className="size-4" />
        </a>
      </>
    ),
  },
  {
    heading: 'Security incidents',
    body: (
      <p>
        If you suspect unauthorised access, lost credentials, disclosure of portal information, or
        another security incident, stop using the affected credentials and report the incident to
        your Phatsema administrator immediately. Do not include passwords or unnecessary personal
        information in the report.
      </p>
    ),
  },
];

const DOCUMENTS: Record<LegalDocumentSlug, LegalDocument> = {
  privacy: {
    title: 'Privacy notice',
    summary: 'How personal information is collected, used, protected, retained, and accessed in the Phatsema Portal.',
    icon: ShieldCheck,
    sections: privacySections,
  },
  'acceptable-use': {
    title: 'Acceptable use and portal disclaimer',
    summary: 'The responsibilities that apply when using this internal operational portal.',
    icon: UserRoundCheck,
    sections: acceptableUseSections,
  },
  paia: {
    title: 'PAIA access to information',
    summary: 'Guidance for formal requests for records under the Promotion of Access to Information Act.',
    icon: FileCheck2,
    sections: paiaSections,
  },
  contact: {
    title: 'Privacy and information access contact',
    summary: 'Where to raise privacy, access-to-information, and security concerns.',
    icon: Mail,
    sections: contactSections,
  },
};

export function LegalPage() {
  const { documentType } = useParams();

  if (!isLegalDocumentSlug(documentType)) {
    return <Navigate to="/legal/privacy" replace />;
  }

  return <LegalDocumentPage documentType={documentType} />;
}

function LegalDocumentPage({ documentType }: { documentType: LegalDocumentSlug }) {
  const document = DOCUMENTS[documentType];
  const DocumentIcon = document.icon;

  useEffect(() => {
    window.document.title = `${document.title} | Phatsema Portal`;
  }, [document.title]);

  return (
    <div className="min-h-screen bg-canvas text-ink">
      <header className="border-b border-line bg-surface">
        <div className="mx-auto flex w-full max-w-[1200px] items-center justify-between gap-4 px-4 py-4 sm:px-6">
          <Link to="/login" className="focus-ring rounded-sm">
            <img src={logoFullColor} alt="Phatsema Projects & Supplies" className="h-10 w-auto" />
          </Link>
          <Link
            to="/dashboard"
            className="focus-ring inline-flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium text-muted hover:bg-sunken hover:text-ink"
          >
            <ArrowLeft aria-hidden className="size-4" />
            Return to portal
          </Link>
        </div>
      </header>

      <main className="mx-auto grid w-full max-w-[1200px] gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[15rem_minmax(0,1fr)] lg:py-12">
        <aside>
          <nav aria-label="Legal information" className="sticky top-6 rounded-lg border border-line bg-surface p-2 shadow-low">
            {LEGAL_ROUTES.map((route) => (
              <Link
                key={route.slug}
                to={`/legal/${route.slug}`}
                className={cn(
                  'focus-ring flex rounded-md px-3 py-2.5 text-sm font-medium',
                  route.slug === documentType
                    ? 'bg-primary-soft text-primary-soft-ink'
                    : 'text-muted hover:bg-sunken hover:text-ink',
                )}
              >
                {route.label}
              </Link>
            ))}
          </nav>
        </aside>

        <article className="min-w-0">
          <div className="rounded-xl border border-line bg-surface p-5 shadow-low sm:p-8 lg:p-10">
            <div className="flex items-start gap-4">
              <span className="grid size-12 shrink-0 place-items-center rounded-lg bg-primary-soft text-primary">
                <DocumentIcon aria-hidden className="size-6" />
              </span>
              <div>
                <p className="text-xs font-semibold tracking-wider text-primary uppercase">Phatsema Portal legal centre</p>
                <h1 className="mt-1 text-2xl font-semibold tracking-tight sm:text-3xl">{document.title}</h1>
                <p className="mt-2 max-w-3xl text-sm leading-6 text-muted">{document.summary}</p>
              </div>
            </div>

            <div className="mt-6 flex gap-3 rounded-lg border border-warning/30 bg-warning-soft p-4 text-sm leading-6 text-warning">
              <Info aria-hidden className="mt-0.5 size-5 shrink-0" />
              <div>
                <p className="font-semibold">{LEGAL_NOTICE_STATUS}</p>
                <p className="mt-0.5">
                  Version {LEGAL_NOTICE_VERSION}. Unconfirmed company particulars are identified
                  clearly and must be approved before production reliance.
                </p>
              </div>
            </div>

            <div className="mt-8 [&_li]:pl-1 [&_ol]:list-decimal [&_ol]:space-y-1.5 [&_ol]:pl-5 [&_ul]:list-disc [&_ul]:space-y-1.5 [&_ul]:pl-5">
              {document.sections.map((section) => (
                <section key={section.heading} className="border-t border-line py-6 first:border-t-0 first:pt-0">
                  <h2 className="text-lg font-semibold tracking-tight">{section.heading}</h2>
                  <div className="mt-3 space-y-3 text-sm leading-6 text-muted">{section.body}</div>
                </section>
              ))}
            </div>

            {documentType === 'privacy' && (
              <div className="grid gap-3 border-t border-line pt-6 sm:grid-cols-3">
                <LegalFact icon={Cookie} title="Essential cookies only" text="Session and CSRF protection." />
                <LegalFact icon={LockKeyhole} title="Controlled access" text="Role and site permissions." />
                <LegalFact icon={Building2} title="Internal operations" text="Inventory and asset workflows." />
              </div>
            )}

            {documentType === 'paia' && (
              <div className="border-t border-line pt-6">
                <a
                  className="inline-flex items-center gap-2 font-medium text-primary hover:underline"
                  href="https://inforegulator.org.za/paia/"
                  target="_blank"
                  rel="noreferrer"
                >
                  Official PAIA information and forms
                  <ExternalLink aria-hidden className="size-4" />
                </a>
              </div>
            )}
          </div>
        </article>
      </main>

      <footer className="border-t border-line bg-surface px-4 py-5 text-center text-xs text-faint">
        <span className="inline-flex items-center gap-2">
          <Scale aria-hidden className="size-3.5" />
          Phatsema Portal legal and privacy information
        </span>
      </footer>
    </div>
  );
}

function LegalFact({
  icon: Icon,
  title,
  text,
}: {
  icon: typeof Cookie;
  title: string;
  text: string;
}) {
  return (
    <div className="rounded-lg bg-sunken p-3">
      <Icon aria-hidden className="size-4 text-primary" />
      <p className="mt-2 text-sm font-semibold text-ink">{title}</p>
      <p className="mt-0.5 text-xs leading-5 text-muted">{text}</p>
    </div>
  );
}
